name: Deploy Lumen App

on:
    push:
        branches:
            - main # O la rama que uses para producción

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository in GitHub runner
              uses: actions/checkout@v3

            - name: Trigger Coolify redeploy
              run: |
                curl -X POST \
                -H "Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_TOKEN }}" \
                -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}" \
                -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" \
                -H "Content-Type: application/json" \
                -d '{"resourceId": "ygkk0o88ckkkk08gcswosoc8"}' \
                "https://dev.lumensaludmental.com/api/v1/deploy"
