name: Deploy Lumen App

on:
    push:
        branches:
            - main # O la rama que uses para producción

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository in GitHub runner
              uses: actions/checkout@v3

            - name: Trigger Coolify redeploy
              run: |
                  curl -X POST \
                    -H "Authorization: Bearer ${{ secrets.COOLIFY_DEPLOY_TOKEN }}" \
                    -H "Content-Type: application/json" \
                    -d '{"resourceId": "ygkk0o88ckkkk08gcswosoc8"}' \
                    "https://app.lumensaludmental.com/api/v1/deploy"
